### ISSUE TITLE
[Spec] Sheet snapping

### ISSUE THREAD

**Issue by haavamoa** [DIPSAS/DIPS.Xamarin.UI#103]
# Sheet snapping
When the user opens the sheet or is dragging the sheet, the sheet should have the ability of snapping into positions. This behavior is quiet common for a modern sheet. 

## Proposed API

XAML:
```xml
<dxui:SheetBehavior SnapPositions="0.2, 0.5, 1.0"
                    SnapStrategy="Nearest,"> <!-- / Direction -->
```
C#:
```csharp
new SheetBehavior() {
    SnapPositions = new double[]{0.2, 0.5, 1.0},
    SnapStrategy = SnapStrategy.Nearest
}
```

- `SnapPositions` = A array of doubles that defines the positions the sheet can snap to. The array should not be set to less than `MinPosition` or more than `MaxPosition`.
 
- `SnapStrategy` = An enum property that will set the strategy of how the sheet determine what snap position it should use when snapping during a drag. 

## When opening
When the sheet is opening and the consumer has set `SnapPositions` but not the `Position` properties, the sheet will do it's best to fit the screen:

- If the calculated position is less than the `SnapPoint[0]` the sheet will snap to the first snap position.
![image](https://user-images.githubusercontent.com/2527084/90317178-cd577180-df27-11ea-9507-695f33ae8551.png)

- If the calculated position is more than the `SnapPoint[0]` the sheet will snap to the next snap position to make sure the user sees all the content. 

If `SnapPositions` is not set, the sheet will be positioned like it is today:

- If the calculated position is less than the `MinPosition`, the sheet will use the `MinPosition`.
- If the calculated position is more than the `MinPosition`, the sheet will use it's calculated position.
- If the calculated position is more than `MaxPosition`, the sheet will use the `MaxPosition`.

## When dragging
When the user has ended a drag, the sheet should use the `SnapPositions` together with the `SnapStrategy` to determine where it should snap to. 

### When dragging
The movement of the sheet to the snapping positions should have a smooth transition with an acceleration.

### When opening
The snapping movement should not be be visible when the sheet is snapping when opening. The sheet should look like it does today with a normal translation from the bottom of the screen to the snap position.

**Comment by haavamoa** [comment]
When opening and the user has defined snap points, the sheet should snap to the lowest snappoint.

Snap points should be between min and max position.

**Comment by haavamoa** [comment]
![image-3](https://user-images.githubusercontent.com/2527084/90261154-dd4e5300-de4c-11ea-91bd-e9a75ad995c3.png)
Here's a little pseudocode me and @Illedan wrote about how it should work when opening

**Comment by haavamoa** [comment]
SnapPositions should be a array of doubles with a TypeConverter that reads a string and return a array of doubles. Easiest to use for both in XAML and C#.

**Comment by mhrastegary77** [comment]
can't wait for it

**Comment by ErlingMK** [comment]
Added with #297
