### ISSUE TITLE
[Enhancement] Add the most common converters

### ISSUE THREAD

**Issue by Illedan** [DIPSAS/DIPS.Xamarin.UI#13]
## Summary
Converters are always needed in XAML projects. We need the most common ones available.

## API Changes
- OppositeBoolConverter
- StringEmptyToBoolConverter with invert
- EmptyListToBoolConverter with invert
- others?

Converters have to implement the `IMarkupExtension` interface to be used inline.

## Intended Use Case
Converters to be used in XAML.

**Comment by haavamoa** [comment]
See what we can do with this: https://gist.github.com/haavamoa/35d0064f72f3d4edc2d705433f2eed0c

This is a `MultiValueConverter`, but it might be useful :)

**Comment by haavamoa** [comment]
Could we rename the `EmptyListConverter` ro `IsEmptyConverter` and make it accept different input values? Example is `IEnumerable` and `string`. Another name could be `IsNullOrEmpty` where we can check more to both `IEnumerable`,  `string` or even `object`. Thoughts?

**Comment by Illedan** [comment]
Agreed. `IsEmptyConverter` handling multiple types is fine. 🚀

**Comment by haavamoa** [comment]
> See what we can do with this: https://gist.github.com/haavamoa/35d0064f72f3d4edc2d705433f2eed0c
> 
> This is a `MultiValueConverter`, but it might be useful :)

There is no `MultiValueConverter` in Xamarin.Forms. If we need it, then we need to implement i `IMultiValueConverter`ourselves.
