### ISSUE TITLE
[Enhancement] Please support UWP

### ISSUE THREAD

**Issue by mhrastegary77** [DIPSAS/DIPS.Xamarin.UI#148]
i know the users of UWP are not like Android & iOS but it's nice to have a desktop (UWP) project along side of mobile AND i love DIPS so i don't wanna remove it because of UWP :(

**Comment by haavamoa** [comment]
Hello @mhrastegary77. Thank you for your comment and thank you for loving DIPS ❤️

We do have a completely different UI project (framework) for our desktop application in DIPS. This project is completely different and have different components that are more suiting for a desktop version. However, this project is not open sourced yet, and I am not sure how easy it is to do so as of now. 
Thank you for posting this issue, I will make sure to forward this message and highlight the need of more open source software internally in DIPS.
