### ISSUE TITLE
[Bug] If a sheet is opened, closed and reopened it remembers the position.

### ISSUE THREAD

**Issue by haavamoa** [DIPSAS/DIPS.Xamarin.UI#150]
### Description

When a sheet is opened, closed and reopened it remembers it's last position. This results in a bad user experience as the sheet (due to calculations) can end up in a different position the next time it opens.

### Steps to Reproduce

1. Create a sheet, set position to 0.7
2. Open the sheet
3. Drag it down to close it
4. Observe that the sheet does not set its position to 0.7

### Expected Behavior
The sheet opens at position = 0.7

### Actual Behavior
The sheet opens at min position

### Basic Information

- Version with issue: 2.12.0
- Last known good version: never

**Comment by mhrastegary77** [comment]
exactly and in UWP it opens full screen at first

**Comment by haavamoa** [comment]
> exactly and in UWP it opens full screen at first

Hi @mhrastegary77 . :) We have decided to not support UWP, so I won't spend time on debugging this for you. But what you can do as a work around is to try tro use our [events](https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Sheet#properties) to set `Position` every time it opens. I think the `OnBeforeOpen` event would be nice to use in this scenario.

**Comment by mhrastegary77** [comment]
i did that actually, no luck :(

**Comment by haavamoa** [comment]
Do you mind adding a reproducible repo for this? I can try to assist you and have a look at your XAML.  

Sheet tries to calculate its position based on the size of the content if you do not set `Position`. If this content is a component that wants to occupy the whole view (CollectionView/ListView) it will automatically go full screen.

**Comment by mhrastegary77** [comment]
thanks for assisting <3
[Sheet test.zip](https://github.com/DIPSAS/DIPS.Xamarin.UI/files/4393888/Sheet.test.zip)

**Comment by haavamoa** [comment]
A complete repository would be appreciated @mhrastegary77 .

**Comment by mhrastegary77** [comment]
so sorry i'm a little bit new in Github :(

[Sheet.zip](https://github.com/DIPSAS/DIPS.Xamarin.UI/files/4394525/Sheet.zip)

**Comment by haavamoa** [comment]
#iOS resetting position
![sheet_notrememberposition_ios](https://user-images.githubusercontent.com/2527084/77802075-67eb0d00-707a-11ea-8742-b2a17ea99bb2.gif)

#iOS not resetting position
`ShouldRememberPosition = "True"`

**Comment by haavamoa** [comment]
> so sorry i'm a little bit new in Github :(
> 
> [Sheet.zip](https://github.com/DIPSAS/DIPS.Xamarin.UI/files/4394525/Sheet.zip)

I looked at your solution @mhrastegary77, and I'm sorry to say that there is not much I can do to help you here. You'r XAML seems fine, but our components are not supporting UWP and there is a lot of bugs with them in UWP. Hope you can find a similar library that can help you with developing UWP apps. I am still fighting to open source more of our organizations library / frameworks, and hopefully one day we can assist you on your way.

**Comment by mhrastegary77** [comment]
thank you so much for giving your time  ❤
