### ISSUE TITLE
[Bug] MenuButton doesn't remember the position

### ISSUE THREAD

**Issue by mhrastegary77** [DIPSAS/DIPS.Xamarin.UI#172]
### Description
MenuButton doesn't stay on top of the ExpandButton when you Rotate your phone!

### Steps to Reproduce
1. Create a FloatingActionMenuBehaviour
2. Create some MenuButtons
3. Click the ExpandButton
3. Rotate your phone!

### Basic Information
- IDE: Visual Studio 16.5.4
- Version with issue: 4.1.1(Latest)
- Last known good version: Unknown
- Android Version: 10

### Screenshots
![Screenshot (594)](https://user-images.githubusercontent.com/42671084/81001357-d7fc6800-8e5c-11ea-95a3-fb2c9f4c36c1.png)
![Screenshot (595)](https://user-images.githubusercontent.com/42671084/81001363-d9c62b80-8e5c-11ea-84f2-8010fc514524.png)

**Comment by haavamoa** [comment]
Thank you for your issue. We do not allow our apps to be rotated internally, so supporting this has not been prioritized. I will have to discuss this internally in order to get this prioritized, so I can not promise you anything as of when it will be fixed.

**Comment by mhrastegary77** [comment]
Thanks you ❤

**Comment by Illedan** [comment]
@mhrastegary77 this should be fixed in v4.1.4. Let me know if there is any issues :)

**Comment by mhrastegary77** [comment]
Thanks it fixed! and fixed the other bug #178 :) ❤
