### ISSUE TITLE
[Bug] iOS: IsDraggable and CloseOnOverlayTapped not working

### ISSUE THREAD

**Issue by mhrastegary77** [DIPSAS/DIPS.Xamarin.UI#178]
### Description
IsDraggable and CloseOnOverlayTapped works fine on android but not working on iOS!

### Steps to Reproduce
1. Create a sheet
2. set CloseOnOverlayTapped="true" and IsDraggable="true"

### Basic Information
- Version with issue: Latest
- Last known good version:Unknown 
- Xamarin.Forms 4.6

### Screenshots
![promax11](https://user-images.githubusercontent.com/42671084/81799572-c3883180-9526-11ea-93e0-853426e18067.gif)

**Comment by haavamoa** [comment]
Hello @mhrastegary77 , I just changed our samples app to have `IsDraggable` and `CloseOnOverlayTapped` to `true` and it works for both Android and iOS.

Do you mind sending me a reproducible project? Preferably a github repository.

**Comment by mhrastegary77** [comment]
@haavamoa fixed in v4.1.4
