### ISSUE TITLE
[Bug]  Type dxui:SheetBehavior not found in xmlns http://dips.xamarin.ui.com

### ISSUE THREAD

**Issue by Saqo1995s** [DIPSAS/DIPS.Xamarin.UI#182]
Just installed from NuGet.org and do the first step in wiki.

**Comment by haavamoa** [comment]
Hello @Saqo1995s and thank you for your submittion. I can see that we have totally forgot to add the importance of doing these steps before using our component:
https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Getting-Started#custom-namespaces

Please try this and let me known if it didn't solve your problem. 

I will update wikis. 👍

**Comment by Saqo1995s** [comment]
> Hello @Saqo1995s and thank you for your submittion. I can see that we have totally forgot to add the importance of doing these steps before using our component:
> https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Getting-Started#custom-namespaces
> 
> Please try this and let me known if it didn't solve your problem.
> 
> I will update wikis. 👍

Yes, it works thank you for the quick answer!
