### ISSUE TITLE
 [Spec] Toast control

### ISSUE THREAD

**Issue by rizanzaky** [DIPSAS/DIPS.Xamarin.UI#196]
## Summary
A toaster view that appears on top of the presented page

## API Changes

Add the toast control

e.g.

Some feature would be,

```csharp
    Toaster.Current.FontSize = 13;
    Toaster.Current.TextColor = Color.White;
    Toaster.Current.BackgroundColor = Color.DodgerBlue;
    Toaster.Current.CornerRadius = 8;
    Toaster.Current.Padding = new Thickness(20, 10);
    Toaster.Current.PositionY = 30;
    Toaster.Current.AnimateFor = 500;
    Toaster.Current.HideToastIn = 5;
    Toaster.Current.LineBreakMode = LineBreakMode.TailTruncation;
    Toaster.Current.MaxLines = 1;

    ShowToastCommand = new Command(parameter =>
    {
        Toaster.Current.ToastAction = async () =>
        {
            await Toaster.Current.HideToaster();
        };
        Toaster.Current.Text = parameter.ToString();

        Toaster.Current.ShowToaster();
    });
```

## Intended Use Case
To give users short information about service failures and other similar cases.

**Comment by haavamoa** [comment]
This is interesting @rizanzaky .

DXUI has yet to create static API's. So the pattern we choose here will be the pattern for future static API's.

I think we should aim towards two things :
1. Calling the API should feel close to how Xamarin.Forms do it with dialogs. I think we could investigate if we can end up with `App.Current.ShowToast(properties)`. This would involve adding an extension method to MainPage I presume.
2. For us to keep our promises of MVVM and testability we should include a wrapper service of the static api. This would involve `IToastService` with a implementation that has no constructors for our consumers register in their containers to inject into their view models.

If both of these requirements will work, then I think the API's would be easy to recognize and to use with MVVM.

**Comment by haavamoa** [comment]
1. I think the toast default action would be to hide it. If it gets set to something else, then it should do that instead. 

2. When it hides it should reset properties so the next caller would get the default behavior.

**Comment by Illedan** [comment]
Don't think we need to expose this amount of properties on the current instance.

```
    private ToastLayout m_layout = new ToastLayout
    {
        FontSize = 13,
        TextColor = Color.White,
        BackgroundColor = Color.Black,
        CornerRadius = 15
        ...
    };

    Toaster.PushToast(new Toast("title") 
    { 
        Layout = m_layout, 
        OnClose = () => ReloadData()
    });
```

- `ToastLayout` will only be applied for this 1 Toast request. 
- There is a default Layout
- Clicking the toast will always close it, but you can choose to do something if you want.
- The `Toast` instance we send in, could contain a method for Hiding/closing it. If data suddenly is available and the toast is no longer needed
- Multiple requests from different services should not override previous toasts. Enable showing multiple at once?

**Comment by rizanzaky** [comment]
The `Layout` attribute looks cleaner 👍

**Comment by rizanzaky** [comment]
> Don't think we need to expose this amount of properties on the current instance.
> 
> ```
>     private ToastLayout m_layout = new ToastLayout
>     {
>         FontSize = 13,
>         TextColor = Color.White,
>         BackgroundColor = Color.Black,
>         CornerRadius = 15
>         ...
>     };
> 
>     App.Current.MainPage.PushToast(new Toast("title") 
>     { 
>         Layout = m_layout, 
>         OnClose = () => ReloadData()
>     });
> ```
> 
>     * `ToastLayout` will only be applied for this 1 Toast request.
> 
>     * There is a default Layout
> 
>     * Clicking the toast will always close it, but you can choose to do something if you want.
> 
>     * The `Toast` instance we send in, could contain a method for Hiding/closing it. If data suddenly is available and the toast is no longer needed
> 
>     * Multiple requests from different services should not override previous toasts. Enable showing multiple at once?

**Comment by haavamoa** [comment]
`App.Current.MainPage.PushToast(new Toast("title") ` => `App.Current.MainPage.DisplayToast(new Toast("title") `

To keep the syntax similar to:
`App.Current.MainPage`.DisplayDialog()`

**Comment by haavamoa** [comment]
If more than one toast is visible at a time, I think they should animate on top of each other with the most recent one at the top. What do you guys think?

**Comment by jonathanrandev** [comment]
Is it possible to have a custom animation to make the toast appear and disappear? 
Eg: Appear from top?

**Comment by haavamoa** [comment]
> Is it possible to have a custom animation to make the toast appear and disappear?
> Eg: Appear from top?

> Also can we allow adding shadows?
We should include a `HasShadow` property.
 For the implementation ;
iOS ; bind the frame `HasShadow` to the same property. 
Android ; Set [VisualElement.Elavation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/visual element-elevation) when `HasShadow` is set

**Comment by rizanzaky** [comment]
> > * Multiple requests from different services should not override previous toasts. Enable showing multiple at once?
> 
> If more than one toast is visible at a time, I think they should animate on top of each other with the most recent one at the top. What do you guys think?

does this mean only one toast appear in a given time?

**Comment by haavamoa** [comment]
> > > * Multiple requests from different services should not override previous toasts. Enable showing multiple at once?
> > 
> > 
> > If more than one toast is visible at a time, I think they should animate on top of each other with the most recent one at the top. What do you guys think?
> 
> does this mean only one toast appear in a given time?

No, I mean that the toasts probably should be stacked vertically. But this is a design question that we should ask our internal UX team about.

**Comment by rizanzaky** [comment]
to make it simple, would go with this approach,

`DisplayToast(string text, ToastOptions toastOptions = null, ToastLayout toastLayout = null);`

```
class ToastOptions {
    ToastAction { get; set; }
    DisplayAnimation { get; set; }
    CloseAnimation { get; set; }
    HideToastIn { get; set; }
}

class ToastLayout {
    BackgroundColor { get; set; }
    CornerRadius { get; set; }
    FontFamily { get; set; }
    FontSize { get; set; }
    HasShadow { get; set; }
    LineBreakMode { get; set; }
    MaxLines { get; set; }
    Padding { get; set; }
    PositionY { get; set; }
    TextColor { get; set; }
}
```

which will avoid conflicts for the same resource as also discussed in the comments

**Comment by ErlingMK** [comment]
> > Also can we allow adding shadows?
> 
> We should include a `HasShadow` property.
> For the implementation ;
> iOS ; bind the frame `HasShadow` to the same property.
> Android ; Set VisualElement.Elavation(https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/visualelement-elevation) when `HasShadow` is set

The ideal solution for shadows would be to not use frames. The frame shadow for iOS doesn't look good at all. Both iOS and Android have platform specific solutions, but they don't work with Xamarin.Forms frames out of the box.
