### ISSUE TITLE
[Enhancement] Enable clicking on items on SlidableContentLayout to scroll towards it

### ISSUE THREAD

**Issue by Illedan** [DIPSAS/DIPS.Xamarin.UI#210]
## Summary
The consumer should be able to enable tapping to scroll to items

## API Changes

```xml
    ScrollOnTap="true"
```

Default value should be false.

**Comment by haavamoa** [comment]
This has been resolved. The consumer can now set a GestureRecognizer and use the ScrollTo method. Closing issue
