### ISSUE TITLE
[Enhancement] Allow configuration of Sheet auto close percentage

### ISSUE THREAD

**Issue by TrueGeek** [DIPSAS/DIPS.Xamarin.UI#215]
## Summary
The Sheet currently auto closes at 0.05. It'd be great if this could be configurable.

## API Changes

A new property would be required

`<dxui:SheetBehavior AutoClosePosition`

Also, MinPosition currently assumes that this value is always 0.05 so something may need to change there.

## Intended Use Case

This would be useful for users who have trouble dragging the Sheet down completely.

Thank you!

**Comment by haavamoa** [comment]
Hello @TrueGeek and thank you for the issue!

This is actually something that I thought of when doing the initial development of the sheet. I did not end up with adding support for it.

I will look in to it, but can not promiss any date for it.

In the mean time you can:

- Subscribe to `OnPositionChanged`
- Use the `PositionEventArgs` to determine what position you would close the sheet.
- Use `sender` to get the sheet instance 
- Set `sheet.IsOpen = false` when the position you want.

Hope this helps and enables you to automatically close it at a different position until we add a property you can use. 👍

**Comment by TrueGeek** [comment]
@haavamoa that workaround worked great! Thank you so much.

**Comment by haavamoa** [comment]
Glad it helped. I updated the sheets FAQ wiki about this work around : https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Sheet-FAQ#auto-close-position

**Comment by haavamoa** [comment]
I realize that `MinPosition` is a bit confusing if we add a `AutoClosePosition`.

I think a better API would be to do the following:
