### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by TrueGeek** [DIPSAS/DIPS.Xamarin.UI#219]
Forgive me if I'm missing something really obvious but I see that v6.0.0 just came out. I can't find release notes anywhere. Our app is using Sheets in production and I'd like to check the release notes for breaking changes / new features before updating our nuget package.

Thanks!

**Comment by haavamoa** [comment]
Hello @TrueGeek, you can find our release notes under github releases.
https://github.com/DIPSAS/DIPS.Xamarin.UI/releases/

Version 6.0.0 is here :
https://github.com/DIPSAS/DIPS.Xamarin.UI/releases/tag/v6.0.0
