### ISSUE TITLE
[Bug]Collection view on Sheet causes sheet to not display on second isOpen = true 

### ISSUE THREAD

**Issue by kmvickers** [DIPSAS/DIPS.Xamarin.UI#230]
Having a sheet with a collection view in the layout .. calling isopen = true the first time displays correctly , hiding and then re showing causes the overlay to show but no sheet view 

### Steps to Reproduce

1.  create sheet with collection view binding to collection 
2. set isopen to true .. sheet displays
3. cancel sheet 
4. set isopen back to true .. 

### Expected Behavior

sheet shouldd redisplay 

### Actual Behavior

overlay is shown but no sheet 

### Basic Information

- Version with issue:
- Last known good version:

### Reproduction Link

working on putting into sample

**Comment by haavamoa** [comment]
Hello @kmvickers and thank for your issue.

I fail to reproduce your bug with the following xaml:
```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="DIPS.Xamarin.Forms.IssuesRepro.Github230.Github230"
             xmlns:dxui="http://dips.xamarin.ui.com">
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Open"
                     Clicked="ToolbarItem_Clicked" />
    </ContentPage.ToolbarItems>
    <dxui:ModalityLayout>
        <dxui:ModalityLayout.Behaviors>
            <dxui:SheetBehavior x:Name="Sheet">
                <StackLayout HeightRequest="200"
                                     BackgroundColor="Red" />
            </dxui:SheetBehavior>
        </dxui:ModalityLayout.Behaviors>
        <CollectionView>
            <CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>A</x:String>
                    <x:String>B</x:String>
                    <x:String>C</x:String>
                    <x:String>D</x:String>
                </x:Array>
            </CollectionView.ItemsSource>
        </CollectionView>
    </dxui:ModalityLayout>
</ContentPage>
```
The codebehind file only has the toolbar item click event that opens the sheet.

Do you mind pasting your XAML?

**Comment by haavamoa** [comment]
I might have misunderstood what you mean by "collectionview in the layout". Are you saying that you are using a collectionview inside of the sheet layout, or in the modality layout?

**Comment by haavamoa** [comment]
I tried to add a collectionview and a button that closes the sheet with the same page:
```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="DIPS.Xamarin.Forms.IssuesRepro.Github230.Github230"
             xmlns:dxui="http://dips.xamarin.ui.com">
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Open"
                     Clicked="ToolbarItem_Clicked" />
    </ContentPage.ToolbarItems>
    <dxui:ModalityLayout>
        <dxui:ModalityLayout.Behaviors>
            <dxui:SheetBehavior x:Name="Sheet">
                <StackLayout>
                    <Button dxui:Modality.CloseOnClick="True"
                            Text="Close" />
                    <CollectionView>
                        <CollectionView.ItemsSource>
                            <x:Array Type="{x:Type x:String}">
                                <x:String>A</x:String>
                                <x:String>B</x:String>
                                <x:String>C</x:String>
                                <x:String>D</x:String>
                            </x:Array>
                        </CollectionView.ItemsSource>
                    </CollectionView>
                </StackLayout>
            </dxui:SheetBehavior>
        </dxui:ModalityLayout.Behaviors>
    </dxui:ModalityLayout>
</ContentPage>
```
![sheetbug_collectionviewinlayout](https://user-images.githubusercontent.com/2527084/92418015-b2160580-f165-11ea-97d0-e4612a22cb50.gif)

**Comment by kmvickers** [comment]
morning .. 

hmm strange .. I have a sheet with the collection view on the sheet and it fails to show the second time .. but if I simply remove the collection view it shows no problem ..

**Comment by haavamoa** [comment]
Do you mind pasting a reproduceable repository link?

**Comment by kmvickers** [comment]
ill have to try and recreate in a simpler code base ..

**Comment by haavamoa** [comment]
This issue is inactive and we need more information
