### ISSUE TITLE
[Bug] Toast resets the scroll position of the page

### ISSUE THREAD

**Issue by rizanzaky** [DIPSAS/DIPS.Xamarin.UI#232]
### Steps to Reproduce

1. Scroll the page the Toast is to be displayed
2. Wait for the Toast to appear
3. The scroll position resets to the top (Bug)

### Expected Behavior

Scroll position should not change after the Toast appeared

### Actual Behavior

Scroll position resets to the top after the Toast appeared

### Basic Information

- Version with issue: 
- Last known good version:

**Comment by haavamoa** [comment]
Reason : Toast disposes the content of the page when it appears.

**Comment by haavamoa** [comment]
![Screenshot_20200909_124039_com discord](https://user-images.githubusercontent.com/2527084/92588726-b80d0300-f299-11ea-9c9d-95e12392862d.jpg)

Here is a screenshot of @ShaneNeuville from the Xamarin forms teams thoughts about the view getting auto disposed when it's removed and readded.

**Comment by haavamoa** [comment]
@jonathanrandev mentioned that a possible better solution is to change this to use the native toast apis.
