### ISSUE TITLE
[Enhancement] [Trendgraph] Add animation on displaying graphs

### ISSUE THREAD

**Issue by rizanzaky** [DIPSAS/DIPS.Xamarin.UI#237]
## Summary
Add animations to graph bars on displaying to make it more appealing 🤩

![GIF-2020-09-16-12-06-55](https://user-images.githubusercontent.com/8718745/93300908-4bec4b00-f815-11ea-9ae7-1f82af48ba48.gif)

## API Changes

Add a **non-bindable** `TrendAnimation` property `Animate` to switch on or off animations. Default should be `TrendAnimation.GrowAll`

e.g.

In order for my new feature to be awesome, we need to create a new boolean value to indicate that it is awesome.

```xaml
<dxui:TrendGraph
    ...
    Animate="False" />
```

```C#
public class TrendGraph {
    ...
    public TrendAnimation Animation { get; set; } = TrendAnimation.GrowAll;
    ...
}
```

```C#
public enum TrendAnimation {
    None = 0, // no animations
    GrowAll, // growing bars with growing background animation
    GrowAndFade, // growing bars with fading background animation
    GrowAndNone // growing bars with fixed background animation
}
```

## Intended Use Case
Provide an appealing look on displaying the trend graphs

**Comment by haavamoa** [comment]
Awesome request! ⭐

I notice in the gif that the background bar of the trend (gray area) is also changing its height. I think it would look better if that has a constant height and  that only the trend is animating up 👌

**Comment by rizanzaky** [comment]
> Awesome request! ⭐
> 
> I notice in the gif that the background bar of the trend (gray area) is also changing its height. I think it would look better if that has a constant height and that only the trend is animating up 👌

mmm this is how the suggestion would look like, with some fading animations to the back bar

![GIF-2020-09-16-12-32-27](https://user-images.githubusercontent.com/8718745/93303223-c8345d80-f818-11ea-91a6-96d1c9beae25.gif)

**Comment by haavamoa** [comment]
It looks to me as if you have implemented all three animations. Maybe have a enum animation property that has `None`, `Grow` (🎉 ), `GrowWithFade` (🚀), `GrowWithBackground` (👍) and the one that gets the most votes will be the default enum. (Sorry for lack of enum names, naming is hard)

**Comment by rizanzaky** [comment]
> It looks to me as if you have implemented all three animations. Maybe have a enum `Animation` property that has `None`, `Grow` (🎉 ), `GrowWithFade` (🚀), `GrowWithBackground` (👍) and the one that gets the most votes will be the default enum. (Sorry for lack of enum names, naming is hard)

mmm yep, will update the request too
