### ISSUE TITLE
[Bug] Binding errors in Popup before BindingContext is set

### ISSUE THREAD

**Issue by Illedan** [DIPSAS/DIPS.Xamarin.UI#242]
### Description

UI is created before BindingContext is set, causing binding erros to occur.

### Expected Behavior

UI class created, BindingContext set, UI Initialised.

### Actual Behavior

UI class created, UI initialised, BindingContext set.

### Basic Information

- Last known good version: Never

**Comment by haavamoa** [comment]
Might want to change the way we create content to use a datatemplate like sheet is doing. 👌

**Comment by haavamoa** [comment]
Closed due to migration to MAUI.
