### ISSUE TITLE
[Bug] Align the padding/ margin between the buttons in sheetView headers 

### ISSUE THREAD

**Issue by Iyani-NK** [DIPSAS/DIPS.Xamarin.UI#248]
### Steps to Reproduce

1. To the place where sheetView buttons is required to align.
 

### Expected Behavior
1. Align the 'CancelButton' to left
2. Align the  'ActionButton' to right

### Actual Behavior
1.  Two different alignment behaviours in iOS and android devices

**Comment by haavamoa** [comment]
The padding / margin of the buttons should be set to the default padding / margin that we are using internally for our apps.
No need to make this set-able until we get any issues from the community.
