### ISSUE TITLE
[Bug] [Slidable] View elements cached and is updated on scrolling

### ISSUE THREAD

**Issue by rizanzaky** [DIPSAS/DIPS.Xamarin.UI#249]
### Steps to Reproduce

1. Change element count in slidable layout with binding
2. Initial count is displayed even after the count is changed
3. When sliding the layout the actual count is updated

### Expected Behavior

The slidable layout should update the count when binding value changes

### Basic Information

- Version with issue: latest
- Last known good version:

**Comment by haavamoa** [comment]
This issue is unclear. What is meant by ‘count’ here?

**Comment by haavamoa** [comment]
This can be resolved by calling Redraw method from this PR: https://github.com/DIPSAS/DIPS.Xamarin.UI/pull/303
