### ISSUE TITLE
[Bug] Sheet doesn't resize the its content when the position change

### ISSUE THREAD

**Issue by tharikadahanayaka** [DIPSAS/DIPS.Xamarin.UI#256]
When there is a long content (a list), the content can not be fully displayed when the sheet view is resized.

![Sheet view issue](https://user-images.githubusercontent.com/33151050/104884201-fde68000-598b-11eb-8bb0-7521f7d44812.gif)

**Comment by haavamoa** [comment]
Closed by #270
