### ISSUE TITLE
[Question] Sheet Header always visibile

### ISSUE THREAD

**Issue by AlleSchonWeg** [DIPSAS/DIPS.Xamarin.UI#260]
Hi,

i tested your sheet component and i have a question:
Is it possible to have the header with the handle always visible to indicate to the user that there is a sheet?

Thank you

**Comment by haavamoa** [comment]
Hello @AlleSchonWeg and thank you for testing our library! 

Unfortunately this is not something that we have added as of yet, but I can definitely see why you would want that. 
I can't think of a "hacky" way for you to enable this as the entire feature is built around having a layout behind the sheet that should close the sheet when tapping or using it.

It would be interesting to add this, but as of right now I can not make any promises that this will be added in the near future 😢

**Comment by AlleSchonWeg** [comment]
Thank you.
I tested a litte bit more and i hope you could help me again ;)
```
		<dxui:ModalityLayout x:Name="modalLayout" OverlayColor="Transparent">
			<dxui:ModalityLayout.Behaviors>
				<dxui:SheetBehavior IsOpen="True"
									x:Name="bottomSheet"
									Alignment="Bottom"
									ContentColor="BlanchedAlmond"
									HeaderColor="Red"
									CloseOnOverlayTapped="True"
									OnPositionChanged="bottomSheet_OnPositionChanged"
									OnClose="bottomSheet_OnClose"
									OnBeforeClose="SheetBehavior_OnBeforeClose"
									ShouldAutoClose="False"
									IsDraggable="True"
									Position="0.04"
									MinPosition="0.04"
									MaxPosition="0.9">
					<dxui:SheetBehavior.SheetContentTemplate>
						<DataTemplate>
							<!-- sheet content goes here -->
							<StackLayout>
								<Label Text="test sheet" />
								<Label Text="test sheet" />
								<Label Text="test sheet" />
								<Label Text="test sheet" />
								<Label Text="test sheet" />
								<Label Text="test sheet" />
							</StackLayout>
						</DataTemplate>
					</dxui:SheetBehavior.SheetContentTemplate>
				</dxui:SheetBehavior>
			</dxui:ModalityLayout.Behaviors>
```
This example avoids to hide the handlebar. But there are few things i hope you could help.
- If the page is appearing the DataTemplate is visible. How can i avoid this? I thought setting Position=0.04 helps, but it is ignored.
- It is possible to get the percental height of the header? So i could set MinPosition to this height.
- I tried in bottomSheet_OnClose to set IsOpen back to true. This generates a exception. Setting IsOpen=true in SheetBehavior_OnBeforeClose works, but the animation flickers.

Thanks again 👍
