### ISSUE TITLE
[Bug] -  the project does not compile on any platform, error Cannot resolve type SheetBehavior

### ISSUE THREAD

**Issue by Cr15Denis** [DIPSAS/DIPS.Xamarin.UI#264]
Visual Studio 2019 - 16.9.3
Xamarin Forms - 5.0.0.2012
DIPS.Xamarin.UI - 6.8.0

![Captura2](https://user-images.githubusercontent.com/70722700/114251087-003df200-995d-11eb-9708-785a93ef8406.PNG)
![error](https://user-images.githubusercontent.com/70722700/114251111-18157600-995d-11eb-91a0-c0c4931ae023.PNG)

**Comment by haavamoa** [comment]
Hello @Cr15Denis, nice to see that you want to use our sheet component. Have you made sure to initialize the library in your shared project like mentioned here?
https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Getting-Started#shared-code-pcl

**Comment by Cr15Denis** [comment]
@haavamoa Thank you very much, I had not seen it. I had only seen this https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Sheet
