### ISSUE TITLE
[Enhancement] - IsDraggable wrap content to sheetbehavior

### ISSUE THREAD

**Issue by Cr15Denis** [DIPSAS/DIPS.Xamarin.UI#265]
It is possible that the SheetBehavior adjusts to the content, when the user swipes up and if he releases he should return to the position adjusted by the content.

The proposed functionality is similar to Minposition, if I slide down and release the sheetBehavior it returns to the minimum position. In this case it is the other way around, if the position is greater than the minimum but if the content does not occupy the full size of the sheetbehavior that slides down, adjusting the sheetbehavior to the content. I hope you understand me

![Captura3](https://user-images.githubusercontent.com/70722700/114284977-e827aa80-9a10-11eb-873c-85d68e142659.PNG)

**Comment by haavamoa** [comment]
Unfortunately not built in. It sounds like you want the [snapping feature](https://github.com/DIPSAS/DIPS.Xamarin.UI/issues/103).

For the time being, what you can do is to use our `OnPositionChanged ` event and do it yourself.

**Comment by Cr15Denis** [comment]
@haavamoa, ok, Excellent control, congratulations, it took a long time to find it :), do you have any C # documentation? Greetings

**Comment by haavamoa** [comment]
> @haavamoa, ok, Excellent control, congratulations, it took a long time to find it :), do you have any C # documentation? Greetings

 No I don't. What you can do is to create a array of positions, subscribe to `OnPositionChanged` and check which position the sheet bahviors position is closest to whenever that event gets raised. Whenever you find a position you can set the SheetBehavior position to that position.

**Comment by Cr15Denis** [comment]
Thanks, I'll be experimenting with the control. With another proposal I found this other control https://github.com/JimmyPun610/Plugin.XF.Backdrop. This control is designed as a view which avoids deactivating the navigationpage manually, you should explore it, maybe you would take some idea to implement it in your control, if you need the example of the image I will gladly share it with you.
![df](https://user-images.githubusercontent.com/70722700/114320451-3c935e80-9ad3-11eb-85a9-c52b74487eb3.PNG)

**Comment by haavamoa** [comment]
> Thanks, I'll be experimenting with the control. With another proposal I found this other control https://github.com/JimmyPun610/Plugin.XF.Backdrop. This control is designed as a view which avoids deactivating the navigationpage manually, you should explore it, maybe you would take some idea to implement it in your control, if you need the example of the image I will gladly share it with you.
> ![df](https://user-images.githubusercontent.com/70722700/114320451-3c935e80-9ad3-11eb-85a9-c52b74487eb3.PNG)

From what I undertood by this comment I presume you would like for the sheet to lay ontop of the navigation page? Maybe this is something you want to stop the users from navigating back when the sheet is opened?

The link you provided was actually not a view, but a page that lays on top of the current stack. Not sure if that is the pattern we want to follow for this component for a potential implementation to get the sheet to lay on top of the navigation page. 

I am not sure if we will implement this as it will require a lot of changes to the current implementation and we have not stumbled upon a UX use case where there is a requirement to block the entire navigation page. We do have a couple of use cases where we have to disable going back when the sheets are opened (for sheets where the user inputs data and save it to the server). This is done through custom renderes on iOS and handling navigation back for Android to ask the user if they want to go back and discard their current work.

**Comment by haavamoa** [comment]
I am closing this issue and refering it in this issue instead :) https://github.com/DIPSAS/DIPS.Xamarin.UI/issues/103

Hope you can find a work around until we get snapping prioritized internally. It is something we want our sheet to support.

**Comment by Cr15Denis** [comment]
It was just an idea, thank you very much, I understand, no problem. Good work, keep up the good work, your control will help me a lot
