### ISSUE TITLE
[Enhancement] - share demo

### ISSUE THREAD

**Issue by Cr15Denis** [DIPSAS/DIPS.Xamarin.UI#267]
Hi, it's me again, sorry for writing so much, I'm interested in using your control for a project that I have, could you give me this example, I couldn't find the code :(. Do you have any email to communicate directly with you so as not to create an issue on github

![Capturasw](https://user-images.githubusercontent.com/70722700/114334193-4afb6d80-9b07-11eb-8eb1-54c3bca713f8.PNG)

**Comment by haavamoa** [comment]
Don't worry about using issues, it's not a problem at all.

This is the Samples project that is a part of our repository here : https://github.com/DIPSAS/DIPS.Xamarin.UI/tree/master/src/Samples

Just for DIPS.Xamarin.UI, open up the solution and select either android or ios samples project to use it.
