### ISSUE TITLE
[Enhancement] Vertical Slidable layout

### ISSUE THREAD

**Issue by Sarthak261995** [DIPSAS/DIPS.Xamarin.UI#271]
## Summary
Slidable layout can have vertical orientation so that user can slide in vertical direction.

It can help developer to achieve something like below

![image](https://user-images.githubusercontent.com/42297422/118388336-72cb7d00-b641-11eb-8c50-ed6c3afb9b7a.png)

Here we are having three vertical slidable layout in a popup
You can slide vertically and centered item will highlighted.

**Comment by haavamoa** [comment]
Hi and thank you for the issue! This sounds like a great idea, but unfortunately its not something we feel like we need internally yet. 

On a sidenote; Datepickers can be troublesome to create yourself, we have decided to go for the built in ones from Android and iOS. 😅

Sorry for the extremely late reply and have a nice day 👍

**Comment by haavamoa** [comment]
Hi and thank you for the issue! This sounds like a great idea, but unfortunately its not something we feel like we need internally yet. 

On a sidenote; Datepickers can be troublesome to create yourself, we have decided to go for the built in ones from Android and iOS. 😅

Sorry for the extremely late reply and have a nice day 👍
