### ISSUE TITLE
[Enhancement] Support displaying an activity indicator in the sheet view

### ISSUE THREAD

**Issue by jonathanrandev** [DIPSAS/DIPS.Xamarin.UI#276]
## Summary
Provide support from SheetView to allow displaying an activity indicator that can be bound to. This would mean that the sheet view is more responsible for toggling its content and the activity indicator. 

## API Changes

TBD

## Intended Use Case
When the Sheet view is displayed in an application it may be initially displayed at various heights ranging on the requirement. If there is an operation that takes time (eg: network operation), the sheet view must display a loading indicator. With the current implementation, unless `VerticalContentAlignment = "SameAsSheet"` is set, displaying an activity indicator in the centre of the screen while the sheet view is at 50% would mean that the activity indicator is hidden. 

Introduction of this enhancement should allow displaying an activity indicator in the centre of the sheet, regardless of the height of the sheet view

**Comment by haavamoa** [comment]
API Changes:

New property for `SheetBehavior`:
`IsBusy` <- Bindable property

**Comment by ErlingMK** [comment]
Added with #297
