### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by Erdogan34** [DIPSAS/DIPS.Xamarin.UI#294]
Question; If an user quickly swiped the panel, how can I know he wants to close the panel?

How about pan update events? This is important because if draggable box height is near the top position on the screen, it's very hard to close the draggable panel. If we can calculate the time diff between start and end time, we can understand that user wants to close the panel. 

Or... 
Is there any solution to close the panel if it's near on the top of the screen?

**Comment by haavamoa** [comment]
We hope the new release will solve your problems @Erdogan34 👍

**Comment by Erdogan34** [comment]
Today, I was able to try it, thank you!

**Comment by Erdogan34** [comment]
Hi @haavamoa, @ErlingMK. 

After update some properties dissappointing like Min-MaxPosition, ShouldAutoClose etc. What is the reason?

Thanks

**Comment by Erdogan34** [comment]
Epic changes! Thank you so much.
