### ISSUE TITLE
[Enhancement] Sheet could intercept gesture when scrollable content reaches the top

### ISSUE THREAD

**Issue by ErlingMK** [DIPSAS/DIPS.Xamarin.UI#299]
## Summary
If the content of the sheet is scrollable and the user scrolls to the top the sheet view could intercept the gesture and start moving downwards. Then the user can get the feel of scrolling the whole sheet away. This would be similar to the sheet views in Apple Maps.

## API Changes

Should be able to toggle this behaviour with a bool property. Could use the existing `InterceptDragGesture`.

## Intended Use Case
Sheet views are often used to show scrollable content. Allowing the user to smoothly scroll away the sheet when finished would be beneficial

**Comment by haavamoa** [comment]
This is fixed in our new MAUI library, we wont fix this for our Xamarin version.

https://github.com/DIPSAS/DIPS.Mobile.UI
