### ISSUE TITLE
[Bug] Sheet Behavior Alignment property was removed

### ISSUE THREAD

**Issue by justintoth** [DIPSAS/DIPS.Xamarin.UI#302]
### Description

The SheetBehavior Alignment property, which was used to align the sheet to the top of the screen, was removed in version 10. Now it gives build errors in Xamarin Forms apps because the property is not recognized.

### Steps to Reproduce

Try to set the Alignment property on a SheetBehavior:

```
<dxui:ModalityLayout>
        <dxui:ModalityLayout.Behaviors>
            <dxui:SheetBehavior
                Alignment="Top"
```

### Expected Behavior

The Alignment property would still exist in version 10, like it did in 9.1.0.

### Actual Behavior

The Alignment property is missing, causing it to have a red squiggly line underneath it in the XAML editor and the project to no longer build.

### Basic Information

- Version with issue: 10+
- Last known good version: 9.1.0

### Screenshots

<img width="710" alt="Screen Shot 2022-01-28 at 10 20 09 PM" src="https://user-images.githubusercontent.com/1443831/151645443-522e30e1-6876-46dd-961f-0a5a7f583c80.png">

**Comment by haavamoa** [comment]
Hi @justintoth . We are sorry to say that the alignment property was decided to be removed as it was not a feature that we used internally and we saw that it was causing issues to our bottom focused sheet. This was announced in the release notes here:
https://github.com/DIPSAS/DIPS.Xamarin.UI/releases/tag/v10.0.0

How does it work for you to downgrade to keep having it?

**Comment by justintoth** [comment]
@haavamoa Yes, I rolled back. I'm surprised that you only support the bottom alignment now, that seems really problematic because when anchoring to the bottom you have to deal with layout / visibility issues when the keyboard is visible. By anchoring to the top you don't have to worry about keyboard implications.

**Comment by haavamoa** [comment]
Fair point, but having access to interactive view elements from bottom is more pleasent for a user as its closer to the thumb. There’s an issue to make sure the view makes space for keyboard here: https://github.com/DIPSAS/DIPS.Xamarin.UI/issues/105

We’ll see if we can reintroduce top alignment if  the demands are high, but right now we want to keep it out of future releases.
