### ISSUE TITLE
[Enhancement] MAUI Support

### ISSUE THREAD

**Issue by snoova** [DIPSAS/DIPS.Xamarin.UI#312]
## Summary

Are there any plans for use in net MAUI?

**Comment by ErlingMK** [comment]
Hello!

Yes, there is but no planned date for it. Depends on when we are able to update our internal projects. Hopefully it will be before the end of this year.

**Comment by bradyguyc** [comment]
Looking forward to the maui version.  Thanks

**Comment by mhrastegari** [comment]
Hopefully with WinUI support.

**Comment by haavamoa** [comment]
Hello, we have started the MAUI jouney in a new project. All components will be migrated over, but some will have some breaking changes when it comes to functionality. Closing this issue.

https://github.com/DIPSAS/DIPS.Mobile.UI
