### ISSUE TITLE
[Bug] Sheet doesn't support orientation changes

### ISSUE THREAD

**Issue by SangI762** [DIPSAS/DIPS.Xamarin.UI#314]
### Description
When you open a sheet and change your device orientation (from portrait to landscape for example) sheet becomes invisible.

### Steps to Reproduce

1. Open sheet in portrait mode, half expanded (first snap point (0.5))
2. Turn device into landscape mode

### Expected Behavior
Sheet should be visible

### Actual Behavior
Sheet is invisible, out of screen bounds.

### Basic Information

- Version with issue: 10.0.4
- Last known good version: NA

### Screenshots

Opened sheet
![Screenshot_1663095360](https://user-images.githubusercontent.com/14075076/189986838-d7619c7d-c06e-4999-9ee1-11a8725af3da.png)

Turned device into landscape mode
![Screenshot_1663095367](https://user-images.githubusercontent.com/14075076/189986845-f4530844-e4c6-4701-b5ec-efeb12abde8a.png)

**Comment by SangI762** [comment]
Found a workaround. Something like this:
```
        public void OrientationChanged()
        {
            bool shouldReopen = false;
            if (IsSheetOpen)
            {
                IsSheetOpen = false;
                shouldReopen = true;
            }
            RaisePropertyChanged(nameof(SheetSnapPoints));
            if (shouldReopen)
                IsSheetOpen = true;
        }
```

**Comment by haavamoa** [comment]
Thank you so much for the issue and the workaround provided. 🥳  This will certainly get looked into as this is not the optimal behaviour from our sheet!

**Comment by haavamoa** [comment]
Fixed in #315 new version should be out soon @SangI762 👍🏻

**Comment by haavamoa** [comment]
https://github.com/DIPSAS/DIPS.Xamarin.UI/releases/tag/v10.0.5 release in 10.0.5 🚀

**Comment by SangI762** [comment]
Wow, thanks for the speed, guys. Will check this out.

**Comment by SangI762** [comment]
So, I checked the latest version and yes, now it works as I wanted initially. But in my use case, I want to adjust snap points on orientation change as well, because it doesn't make sense use the same in landscape mode. So basically if sheet is open and I'm rising SnapPoints property - the sheet doesn't react to it. You have to close and open it again. So in my case my workaround still works better and solves my problem.
