### ISSUE TITLE
[Bug] Sheet doesn't support Xaml compilation

### ISSUE THREAD

**Issue by SangI762** [DIPSAS/DIPS.Xamarin.UI#316]
### Description
Xaml can't be compiled when Sheet is used. 

### Steps to Reproduce

1. Create a page with xaml
2. Add sheet component to it
3. Add `[XamlCompilation(XamlCompilationOptions.Compile)]` attribute on created page.

### Expected Behavior
Code compiled successfully

### Actual Behavior
Error occuried: `Error XFC0000: Cannot resolve type "dxui:SheetBehavior". (XFC0000) XamlC`

### Basic Information

- Version with issue: 10.0.5
- Last known good version: NA

### Workaround
use `[XamlCompilation(XamlCompilationOptions.Skip)]` on pages where sheet is used.

**Comment by haavamoa** [comment]
Hm, this is strange. We use xaml compliations all the time with our apps internally. Have you made sure to follow the getting started? Specifically initializing the library.

https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Getting-Started#api-and-ui-components-usage

**Comment by SangI762** [comment]
Oh, yes, you're right, my bad. I missed initialization and adding it fixed the issue. Big thanks.

**Comment by haavamoa** [comment]
Ive thought about doing the same as Xamarin Community Toolkit to make this easier by code generation, but we’ve not prioritized it yet. Anyway, glad it worked for you 👍
