### ISSUE TITLE
[Spec] Common colors

### ISSUE THREAD

**Issue by haavamoa** [DIPSAS/DIPS.Xamarin.UI#37]
## Summary
The package should provide colors that can be used by the consumers. This will include the common `Theme` colors of a DIPS specific app, but also colors that can be used for status and other color use cases.

## API Changes

- Include a `Colors.xaml` file that can be referenced by our Consumers.
- Each `Color` should have a `x:Key`

e.g:
```xml
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
                    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                    mc:Ignorable="d"
                    x:Class="DIPS.Xamarin.UI.Styles.Colors">

    <Color x:Key="Theme.Primary">#047F89</Color>
```

## Intended Use Case
Consumers that use our library can easily use our colors by referencing the `.xaml` file in their `App.xaml`:
```xml
<ResourceDictionary.MergedDictionaries>
     <ResourceDictionary Source="pack://application:,,,/DIPS.Xamarin.UI;component;Styles/Colors.xaml"/>
</ResourceDictionary.MergedDictionaries>
```

And refer each color in line in a `.xaml` file:
```xml
Color={StaticResource ColorName}
```

**Comment by haavamoa** [comment]
This needs internal clearification before it can me implemented.

**Comment by haavamoa** [comment]
Approved and can be implemented.

**Comment by Illedan** [comment]
The default colours used in the Trend chart should be added here and consumed in the Trend graph.

**Comment by haavamoa** [comment]
We should have a look into this asap. Want to get it in as fast as possible.

**Comment by haavamoa** [comment]
[Wiki has been added](https://github.com/DIPSAS/DIPS.Xamarin.UI/wiki/Colors)
