### ISSUE TITLE
[Bug] Can't have dxui:Popup.CloseOnClick="True" on RadioButtonGroup

### ISSUE THREAD

**Issue by Illedan** [DIPSAS/DIPS.Xamarin.UI#63]
### Description
Can't have RadioButtonGroup as the `CloseOnClick` source for a popup

### Steps to Reproduce

```xml
<dxui:RadioButtonGroup Grid.Row="0"
                        HorizontalOptions="FillAndExpand"
                        ItemsSource="{Binding HostNames}"
                        SelectedItem="{Binding SelectedHost}"
                        SelectedItemChangedCommand="{Binding SaveCommand}"
                        dxui:Popup.CloseOnClick="True"
                        SeparatorColor="Transparent"/>
```

### Expected Behavior
Popup should close when selection is done

### Actual Behavior
Popup is not closed.

### Basic Information
- Version with issue: 1.0.0

**Comment by haavamoa** [comment]
Closed because `RadioButtonGroup` can not handle that it is inside of a popup that wants to close when you select a item.
After discussion, we ended up with that the consumers probably should not use a radio button group for this scenario if it wants to close when you select.
