### ISSUE TITLE
[Enhancement] Popup should have more flexibility

### ISSUE THREAD

**Issue by Illedan** [DIPSAS/DIPS.Xamarin.UI#65]
## Summary
- Should be able to place popup directly above the button clicked with `Direction="Center"`.
- Should be able to force popup to fill the width.

## API Changes
PopupDirection should get a `Center` property.

PopupBehavior should check the childs `HorizontalAlignment` for it to fill the width.

## Intended Use Case
```xml
<dxui:PopupBehavior BindingContextFactory="{Binding HostSelectionViewModelFactory}"
                                                  Direction="Center">
    <Frame HorizontalAlignment="FillAndExpand">
```

**Comment by haavamoa** [comment]
Should the consumer be able to set directions to `center` and `below` / `above`?  If so, we need to add `CenterAbove` and `CenterBelow`.

A more interesting approach would be to enable [Flags] enum and that the consumer can det directions with `Direction="Center, Above". This can be achieved by using a `TypeConverter`.

[Here](https://stackoverflow.com/questions/7718928/setting-multiple-enum-flags-in-xaml) is an example WPF.

**Comment by Illedan** [comment]
I like the idea of flags.
