### ISSUE TITLE
[Spec] SlidableLayout

### ISSUE THREAD

**Issue by Illedan** [DIPSAS/DIPS.Xamarin.UI#68]
## Summary
A component to navigate through items with some sense of acceleration.
Now we only have panels/layouts which supports navigating through 1 and 1 item. And without the sense of how far away the next item is.

## API Changes

Need to create a new Component which can be used like:

```xml
<SlidableLayout OnSlidingCommand=""
                OnStopCommand=""
                ItemTemplate=""
                ViewModelFactory=""
                SlideProperties=""

```

```csharp
public struct SlideProperties
{
    public double Position{get; set;}
    public int HoldId{get; set;}
    public bool IsHeld{get; set;}
}
```

`OnSlidingCommand` occurs when the panel is sliding through values, but not stopping. Here the consumer could change the UI with cached data or show some placeholder. This command takes an `int`, relative to the start position of `0`.
`OnStopCommand ` occurs when the panel has stoped sliding (or are going to) and a value will be selected. Here the consumer should load data if needed. This command takes an `int`, relative to the start position of `0`.
`ItemTemplate` template to be shown on each value having `BindingContext` set from `ViewModelFactory`.
`ViewModelFactory` should be a `Func<int, object>` which takes an int for the position relative to `0` and generates a ViewModel to be used as the `BindingContext` for the template.
`SlideProperties` is only used by the panel itself, but if you want to have multiple panels with the same features, you can use this property to communicate between them. So that only 1 can navigate at a time. Set this with wanted `Position` if you need the initial value to be other than `0`. 

## Intended Use Case
In a sliding calendar component or while navigating through a list of items smoothly.

**Comment by haavamoa** [comment]
What is `HoldId` and `IsHeldId`?

Not sure if I understand how I should compose my `ViewModelFactory`. Will the factory be used to dertemine a view model for each `int` in the sliding panel?

Could you Include a more complete example, with an view model? This can help out the examples.

**Comment by Illedan** [comment]
`SlideProperties` is not to be used by consumers. It is for a panel to communicate between other panels of the same type in the same view. `HoldId`/`IsHeld` is to ensure only 1 of these panels can slide with the finger at the same time. (as you can perform multitouch)

**Comment by haavamoa** [comment]
> Not sure if I understand how I should compose my `ViewModelFactory`. Will the factory be used to dertemine a view model for each `int` in the sliding panel?
> 
> Could you Include a more complete example, with an view model? This can help out the examples.
?

**Comment by Illedan** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/1519936/70932592-189b4680-2060-11ea-9e28-3ccf20e9c0e0.png">

I added a branch task/ekv-slidingPanel which nearly solves this Issue. Only thing missing is some tests and acceleration.
But I think I will do acceleration in another PR/Issue to verify the API with the current logic.
