### ISSUE TITLE
[Enhancement] RadioButtonGroup: Execute code instantly after user selected an item

### ISSUE THREAD

**Issue by darkwood** [DIPSAS/DIPS.Xamarin.UI#72]
## Summary
The consumer of the RadiobuttonGroup should be able to execute code after user selecting an option. 

## Intended Use Case
If I choose an element, I sometimes want to instantly close the popup with the radiobuttongroup control. One use case would be a dropdownlist, wher the list typically collapses when you select an option.

**Comment by haavamoa** [comment]
You can execute code after the user clicks it by binding the `SelectedItemChangedCommand` to an `ICommand`.

If you need to close an popup when the user clicks a  radio button, the popup needs to provide a way of doing that through code.

**Comment by haavamoa** [comment]
This is related to popup, not radiobuttongroup.
Created new issue for popup here : https://github.com/DIPSAS/DIPS.Xamarin.UI/issues/74
