### ISSUE TITLE
[Spec] Sheet

### ISSUE THREAD

**Issue by haavamoa** [DIPSAS/DIPS.Xamarin.UI#94]
## Summary
![iPhone X-XS – 1](https://user-images.githubusercontent.com/2527084/72522637-75a43b00-385e-11ea-97f2-a88030b11a2c.png)

A drag-able sheet with custom content that can either be visible from the bottom or the top. It let's people interact with a different set of actions within a page or to view specific content without being navigated.

### Required properties:
- Background should be grayed when sheet is visible
   - Tapping the grayed area should hide the sheet
- Programmatically set the direction the sheet should display to top or bottom
- Content should be completely customizable.
- Programmatically show/hide the sheet.
- Programmatically set the position of the sheet 
- Hitbox should be a little higher than the sheet, this will be helpful for people when they drag it.
- The component should respect the keyboard and move it's content respectively.

### Optional properties:
- Drag-able by using a handle.
- Snap to snap-points when it is dragged

### Questions:
- Should the component go over the navigation bar when it is full-sized?
    - The component will not go over the navigation bar for the first iterations.

## API Changes

Add a `ModalityLayout` with a new `SheetBehavior`:

```xml
<dxui:ModalityLayout>
        <dxui:ModalityLayout.Behaviors>
            <dxui:SheetBehavior>
                <StackLayout>
                    <Label Text="My label inside of the sheet" />
                </StackLayout>
            </dxui:SheetBehavior>
        </dxui:ModalityLayout.Behaviors>
</dxui:ModalityLayout>
```
### Alignement

The sheet should either be visible from the bottom or at the top of the screen. 

 > The default alignment should be `Bottom` ([pic](https://user-images.githubusercontent.com/2527084/72522637-75a43b00-385e-11ea-97f2-a88030b11a2c.png)). 

```xml
<dxui:SheetBehavior IsOpen="True" 
                    Alignment="Top" />
```

![iPhone X-XS – 1](https://user-images.githubusercontent.com/2527084/72522953-12ff6f00-385f-11ea-9a9a-dad595a26505.png)

### Snapping

When people drag the sheet, it should be able to snap to points on the screen. The position of the points will have to be defined by the consumer. The number of positions should be limited, but can be increased in the future.

Each snap point should be a number between 0-1 (representing 0 - 100% of the screen height)

```xml
<dxui:SheetBehavior IsOpen="True"
                    IsDragable="True"  
                    SnapPoints="0.2, 0.8" />
```

![iPhone X-XS – 1](https://user-images.githubusercontent.com/2527084/72523143-738eac00-385f-11ea-9f33-0768ea096a96.png)

### Set position programmatically

The consumer of the sheet should be able to programatically set the position of the sheet. The provided method should accept a number between 0 - 1 (representing 0 - 100%)

Half size:
```xml
<dxui:SheetBehavior IsOpen="True"
                    Position="0.5" />
```
![iPhone X-XS – 1](https://user-images.githubusercontent.com/2527084/72523220-a2a51d80-385f-11ea-87b8-754fd40f0e45.png)

Full size:
```xml
<dxui:SheetBehavior IsOpen="True"
                    Position="1" />
```
![iPhone X-XS – 1](https://user-images.githubusercontent.com/2527084/72523274-bb153800-385f-11ea-9a6f-92e815a025c9.png)

## References
-https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/
-https://material.io/develop/android/components/bottom-sheet-dialog-fragment/
-[Detect if keyboard is open](https://stackoverflow.com/questions/46360257/xamarin-forms-check-if-keyboard-is-open-or-not)

**Comment by Illedan** [comment]
Small note.
`Direction="Top"` might be a problem on iOS if we allow to drag it all the way down. As iOS has the AppSwitcher for dragging up.

**Comment by haavamoa** [comment]
> `Direction="Top"` might be a problem on iOS if we allow to drag it all the way down. As iOS has the AppSwitcher for dragging up.

I believe that ias long as the page that uses this component has respected the [`Safe Area`](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-safe-area-layout) it will be not be a problem.

**Comment by haavamoa** [comment]
We should try to reuse `PopupLayout` instead of creating a new layout. Sheet is a popup and needs the same functionally as any other popup when it comes to overlaying and clicking outside of the component.

**Comment by darkwood** [comment]
I think "Direction" is misleading word. I would suggest "Alignment" or "Align"
<SheetView IsOpen="True" 
           Align="Top" />

**Comment by haavamoa** [comment]
I would propose to use behavior on `ModalityLayout` instead of having a control. This is because it feels unatural to create a control that will be visible in the interface when something is triggered. Behavior means that you don't need to create unesseary places in the important content of your page to be able to show this later.

**Comment by kwkgaya** [comment]
The back button should close the modal. The dxui PopupLayout navigates to the previous page.

**Comment by haavamoa** [comment]
> The back button should close the modal. The dxui PopupLayout navigates to the previous page.

Is this discussed with our designers? We have had this discussion before and we did end up with navigating back and not closing the modals when we Tapped the back button. We have created an seperste issue for it : #98

**Comment by kwkgaya** [comment]
> > The back button should close the modal. The dxui PopupLayout navigates to the previous page.
> 
> Is this discussed with our designers? We have had this discussion before and we did end up with navigating back and not closing the modals when we Tapped the back button. We have created an seperste issue for it : #98

I had not discussed this. In the lab result modals that I tested, ux is bad when it navigate to the previous page.

**Comment by haavamoa** [comment]
> > > The back button should close the modal. The dxui PopupLayout navigates to the previous page.
> > 
> > 
> > Is this discussed with our designers? We have had this discussion before and we did end up with navigating back and not closing the modals when we Tapped the back button. We have created an seperste issue for it : #98
> 
> I had not discussed this. In the lab result modals that I tested, ux is bad when it navigate to the previous page.

Let's discuss this internally and demonstrate it. I agree that the back button on Android feels natural that it closes the modal, but it feels unnatural that the back arrow in the navigation bar should close the modal.
