### ISSUE TITLE
[Bug] Closing modals with backbutton instead of navigating back

### ISSUE THREAD

**Issue by Illedan** [DIPSAS/DIPS.Xamarin.UI#98]
### Description

We need to consider if we want backbutton / backswipe to close a popup or navigate to the previous page when a popup/modal is open.

**Comment by haavamoa** [comment]
I thought we discussed this and landed on navigating back @darkwood?

**Comment by kwkgaya** [comment]
I think this can change depending on how the popup is used. Therefore can a property be added to configure this. 
// True to close modal, false to navigate back.
bool CloseOnBackButtonPress;
I vote to default this to true, so that modal closes, instead of navigating by default.

**Comment by haavamoa** [comment]
> I think this can change depending on how the popup is used. Therefore can a property be added to configure this.
> // True to close modal, false to navigate back.
> bool CloseOnBackButtonPress;
> I vote to default this to true, so that modal closes, instead of navigating by default.

Agree on the implementation detail. This should be set on each modal component that is using the `ModalityLayout`, and not set globally for the `ModalityLayout`.

**Comment by haavamoa** [comment]
A question that came to mind. Do we want this to be a part of the popup, or could consumers close popups when they detect the back button pressed? It's not impossible to support it, but it adds complexity as we need to get the current page to detect it

**Comment by kwkgaya** [comment]
> A question that came to mind. Do we want this to be a part of the popup, or could consumers close popups when they detect the back button pressed? It's not impossible to support it, but we need to get the current page to be able to detect it. And as we need to do that, doesn't the responsibility lie with the page (or consumer) instead of with the popup?

Yes, I also think handling it in the consumer page is a better option.

**Comment by haavamoa** [comment]
Closing this as this is the consumers responsibility.
